### ISSUE TITLE
로그인/인증

### ISSUE THREAD

**Issue by cskime** [FinalProject-Team4/iOS_DaangnMarket#10]
## Todo
- [x] UI 구성
- [x] 인증번호 요청 시 버튼 이름 변경
- [x] 인증번호 요청 시 상단 알림
- [x] 입력 오류 효과 추가
- [x] Firebase 전화번호 인증
- [x] 최초 가입 시 닉네임, 프로필 사진 등록 page
- [x] idtoken, user create request 확인
## BugFix
- [x] 키보드 toolBar 이용해서 내리면 인증번호 입력 필드 전환 시 offset 튀는 문제

**Comment by cskime** [comment]
baseUI 완료
