### ISSUE TITLE
Product - 상품 소개 페이지

### ISSUE THREAD

**Issue by cskime** [FinalProject-Team4/iOS_DaangnMarket#7]
## Todo
- [x] custom navigation bar
- 상품이미지 swipe 효과
  - [x] stretching
  - [x] activity indicator view
- [x] 작성자 정보 요약
- [x] 상세내용
- [x] 이 게시글 신고하기(버튼만 만든 상태)
- [x] 사용자의 판매상품(최대 4개까지)
- [x] Bottom buttons(좋아요, 현재가격, 가격제안 가능여부, 채팅으로 거래하기) 버튼만 만들어진 상태

## Note
- 홈 화면에서 피드 탭했을 때 들어가는 페이지
- 중고거래 게시글만 개발하고 추후 일정에 따라 동네홍보 게시글도 추가할 것

- 판매자의 다른 상품은 보류, 추천 상품은 제외
- 상품 소개에 관련된 content에만 집중
  - 사진, 글 제목, 글 내용
  - 작성자 정보 요약
  - 가격, 가격제안
- 기타 버튼들은 만들어만 두고 action은 추후 일정에 따라 개발
  - 공유 및 더보기(새로고침 등 기능 들어있는 것), 신고하기 등
